apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-python-containers
spec:
  vendor: eduk8s.io
  title: Python Containers
  description: An interactive workshop on constructing images for Python applications.
  url: https://github.com/eduk8s-labs/lab-python-containers
  content: github.com/eduk8s-labs/lab-python-containers
  duration: 60m
  session:
    budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      docker:
        enabled: true
      registry:
        enabled: true
